### ISSUE TITLE
[TASK] Create a Game Play class

### ISSUE THREAD

**Issue by titasg** [Ace-Plays-Blackjack/ace-plays-game#56]
### Description
Create a Game Play class that:

- [x] Gets called from processing thread via callback
- [ ] Gets results from processing thread and accumulates them
- [ ] Once accumulated, decides which one is a valid detection
- [ ] Once the valid detection is found, keep the last cards coordinates (corner and mid-point)
- [x] Use the card coordinates to differentiate between the Dealers and Players hands
- [x] Dealer only has one card.
- [ ] Once these detections are finished, store the results in the class.
- [x] Continue with Strategy Engine and LEDs
- [x] Stop Strategy Engine if the player has finished playing. I.e. when STAND is called.
- [x] If the player has busted, then player has lost and game will reset.
- [x] If the Dealers hand is total empty, then the game has finished. (i.e. all cards have been collected and the board is clean)
- [x] Wait for new game to start. (i.e. dont do anything until new cards are dealt)

**Comment by titasg** [comment]
@Eagleeye101 @jijoNV  Have a look through the logic above. We need to also keep track on when the game has started or finished. I was thinking that the game will be finished when there aren't any cards detected on the dealer, i.e. when we sweep the cards and have an empty board.

Let me know if you think this makes sense.

**Comment by Eagleeye101** [comment]
Yeah, I like the logic here. The separate class to do all these things is sensible. Good idea to reset when there is an empty board, but may be difficult to reset when player busts as cards will still be on the table. Probably just easiest to remove all cards after a bust and reset that way

**Comment by titasg** [comment]
@Eagleeye101 did what you suggested here, just check if tehre aren;t any cards, i.e. you clear the board. Feel free to add functionality.

**Comment by titasg** [comment]
Open PR #73.
Some tick boxes are unchecked.

Accumulator has not been solved for example, and the reset case is instead an empty board alltogether.
