### ISSUE TITLE
[TASK] Create a new Card Discriminator Class

### ISSUE THREAD

**Issue by titasg** [Ace-Plays-Blackjack/ace-plays-game#61]
### Description

The method template_matching() in the DetectCard.cpp processing thread can be split further into a new class.
This will allow for future work to use some other methodology in identifying the card rank.

For example, a machine learning model that identifies letters and numbers instead of comparing a template image against the isolated card Rank Region of Interest

**Comment by Eagleeye101** [comment]
Done
